language: go

go:
  - 1.9.2

os:
  - osx

sudo: false

cache:
  directories:
    - vendor

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - make test-all

before_deploy:
  - go get github.com/tcnksm/ghr
  - echo $GITHUB_TOKEN > github_token

deploy:
  provider: script
  script: make release-upload
  on:
    tags: true
    branch: master
